force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <label>Doctor</label>
    <type>Lookup</type>
    <referenceTo>Doctor__c</referenceTo>
    <relationshipName>DoctorAppointments</relationshipName>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <type>Lookup</type>
    <referenceTo>Patient__c</referenceTo>
    <relationshipName>Appointments</relationshipName>
</CustomField>

force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <pluralLabel>Doctors</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Doctor Name</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <pluralLabel>Patients</pluralLabel>
    <nameField>
        <type>Text</type>
        <label>Patient Name</label>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppointmentServiceTest.cls
@isTest
public class AppointmentServiceTest {

    @isTest
    static void testFlow() {

        Patient__c p = new Patient__c(Name='P');
        insert p;

        Doctor__c d = new Doctor__c(Name='D', Availability__c=true);
        insert d;

        Test.startTest();

        Appointment__c a = AppointmentService.createAppointment(
            p.Id,
            d.Id,
            System.now().addDays(1)
        );

        Test.stopTest();

        System.assertNotEquals(null, a.Id);
    }
}